In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv("students.csv")
df

,name,math,cs
0,david,92,98
1,laura,56,68
2,sanjay,88,81
3,wei,70,80
4,jeff,80,83
5,aamir,49,52
6,venkat,65,66
7,virat,35,30
8,arthur,66,68
9,paul,67,73


In [10]:
math = df["math"].values
cs= df['cs'].values
math
cs


array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73], dtype=int64)

In [11]:
print(math)
print(cs)

[92 56 88 70 80 49 65 35 66 67]
[98 68 81 80 83 52 66 30 68 73]


In [12]:
print("Hello")

Hello


In [19]:
import numpy as np

def gradient_descent(x, y):
    m_curr = c_curr = 0
    iterations = 10000
    learning_rate = 0.1
    n = len(x)

    for i in range(iterations):
        y_predicted = m_curr * x + c_curr

        loss = (1 / n) * sum(val**2 for val in (y - y_predicted))

        md = -(2 / n) * sum(x * (y - y_predicted))
        bd = -(2 / n) * sum(y - y_predicted)

        m_curr = m_curr - learning_rate * md
        c_curr = c_curr - learning_rate * bd

        print("m {}, b {}, loss {}, iteration {}".format(
            m_curr, c_curr, loss, i))

gradient_descent(math, cs)

m 989.1800000000002, b 13.980000000000002, loss 5199.1, iteration 0
m -934764.0368, b -13190.280800000002, loss 4624176649.337042, iteration 1
m 884277037.336928, b 12477909.287008, loss 4138149214106179.5, iteration 2
m -836515925792.161, b -11803958877.411753, loss 3.7032060698742374e+21, iteration 3
m 791334463505817.5, b 11166409601495.324, loss 3.3139779370946647e+27, iteration 4
m -7.485933188160774e+17, b -1.0563295304756512e+16, loss 2.965659906666545e+33, iteration 5
m 7.081606865615178e+20, b 9.992756103138988e+18, loss 2.6539520929098406e+39, iteration 6
m -6.699118805714214e+23, b -9.453032567579368e+21, loss 2.37500655271612e+45, iteration 7
m 6.33728949159553e+26, b 8.942460298380127e+24, loss 2.1253797838000865e+51, iteration 8
m -5.995003113846916e+29, b -8.459464792532926e+27, loss 1.9019902156564862e+57, iteration 9
m 5.671204129572697e+32, b 8.002556588265454e+30, loss 1.7020801684605084e+63, iteration 10
m -5.36489400731005e+35, b -7.570326671838513e+33, loss 1.5231

C:\Users\jayag\AppData\Local\Temp\ipykernel_18952\3888300873.py:12: RuntimeWarning: overflow encountered in scalar power
  loss = (1 / n) * sum(val**2 for val in (y - y_predicted))
C:\Users\jayag\AppData\Local\Temp\ipykernel_18952\3888300873.py:10: RuntimeWarning: overflow encountered in multiply
  y_predicted = m_curr * x + c_curr
C:\Users\jayag\AppData\Local\Temp\ipykernel_18952\3888300873.py:14: RuntimeWarning: overflow encountered in multiply
  md = -(2 / n) * sum(x * (y - y_predicted))
C:\Users\jayag\AppData\Local\Temp\ipykernel_18952\3888300873.py:17: RuntimeWarning: invalid value encountered in scalar subtract
  m_curr = m_curr - learning_rate * md
C:\Users\jayag\AppData\Local\Temp\ipykernel_18952\3888300873.py:18: RuntimeWarning: invalid value encountered in scalar subtract
  c_curr = c_curr - learning_rate * bd


m nan, b nan, loss nan, iteration 2640
m nan, b nan, loss nan, iteration 2641
m nan, b nan, loss nan, iteration 2642
m nan, b nan, loss nan, iteration 2643
m nan, b nan, loss nan, iteration 2644
m nan, b nan, loss nan, iteration 2645
m nan, b nan, loss nan, iteration 2646
m nan, b nan, loss nan, iteration 2647
m nan, b nan, loss nan, iteration 2648
m nan, b nan, loss nan, iteration 2649
m nan, b nan, loss nan, iteration 2650
m nan, b nan, loss nan, iteration 2651
m nan, b nan, loss nan, iteration 2652
m nan, b nan, loss nan, iteration 2653
m nan, b nan, loss nan, iteration 2654
m nan, b nan, loss nan, iteration 2655
m nan, b nan, loss nan, iteration 2656
m nan, b nan, loss nan, iteration 2657
m nan, b nan, loss nan, iteration 2658
m nan, b nan, loss nan, iteration 2659
m nan, b nan, loss nan, iteration 2660
m nan, b nan, loss nan, iteration 2661
m nan, b nan, loss nan, iteration 2662
m nan, b nan, loss nan, iteration 2663
m nan, b nan, loss nan, iteration 2664
m nan, b nan, loss nan, i

In [24]:
import numpy as np

def gradient_descent(x, y):
    m_curr = c_curr = 0
    iterations = 1000
    learning_rate = 0.0001
    n = len(x)

    for i in range(iterations):
        y_predicted = m_curr * x + c_curr

        loss = (1/n) * sum(val**2 for val in (y - y_predicted))

        md = -(2/n) * sum(x * (y - y_predicted))
        bd = -(2/n) * sum(y - y_predicted)

        m_curr = m_curr - learning_rate * md
        c_curr = c_curr - learning_rate * bd

        print("m {}, b {}, loss {}, iteration {}".format(
            m_curr, c_curr, loss, i))

gradient_descent(math, cs)

m 0.9891800000000002, b 0.013980000000000001, loss 5199.1, iteration 0
m 1.0416176032, b 0.0147417592, loss 46.3330473650399, iteration 1
m 1.0443971065873279, b 0.014802799669408, loss 31.852649863558305, iteration 2
m 1.0445441606668626, b 0.014826693765467417, loss 31.811952059367805, iteration 3
m 1.0445516647187705, b 0.014848618440205038, loss 31.811832943358482, iteration 4
m 1.0445517710206773, b 0.014870438475874223, loss 31.81182786237329, iteration 5
m 1.0445514851602624, b 0.0148922527273428, loss 31.811823101960222, iteration 6
m 1.0445511785140886, b 0.014914066435056226, loss 31.81181834255699, iteration 7
m 1.0445508707693771, b 0.01493587987682099, loss 31.811813583265543, iteration 8
m 1.0445505629697767, b 0.014957693067366749, loss 31.811808824083364, iteration 9
m 1.044550255170612, b 0.014979506007477059, loss 31.811804065010467, iteration 10
m 1.0445499473748168, b 0.015001318697196186, loss 31.81179930604682, iteration 11
m 1.0445496395825458, b 0.01502313113652